matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
            - libvcflib-tools 
            - vcftools
    - os: linux
      dist: focal
      arch:
        - arm64
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
            - libvcflib-tools 
            - vcftools
    - os: linux
    - os: linux
      dist: focal
      arch:
        - arm64
      compiler: clang
      addons:
        apt:
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
            - libvcflib-tools 
            - vcftools
    - os: linux
script:
  - mkdir build
  - meson build/
  - ninja -C build/
  - meson test --timeout-multiplier 8 --print-errorlogs -C build/
