# Control file for continuous integration testing at http://travis-ci.org/

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
    - os: linux
      dist: focal
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
    - os: linux
      dist: focal
      arch:
        - arm64
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
#  The OSX brew version takes forever to install meson
#    - os: osx
#      compiler: clang

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install meson ninja; fi

script:
  - mkdir build
  - meson build/
  - ninja -C build/
  - meson test -t 8 -C build/
  - cat /home/travis/build/pjotrp/freebayes/build/meson-logs/testlog.txt
