# Control file for continuous integration testing at http://travis-ci.org/

os: linux
language: C++
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
    - os: linux
      arch:
        - arm64
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
    - os: osx
      compiler: clang
      language: shell
      python: 3.8
      cache:
        - directories:
          - $HOME/Library/Caches/pip

# before_install:
#   - git submodule update --init --recursive
#   - gcc --version && g++ --version

# install:
#   - pip install meson ninja

script:
  - meson builddir
  - ninja -C builddir -j 4
  - ninja -C builddir test
