# Control file for continuous integration testing at http://travis-ci.org/

os: linux
language: C++
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
    - os: linux
      arch:
        - arm64
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bc
            - samtools
            - parallel
    - os: osx
      compiler: clang

before_install:
  - git submodule update --init --recursive
  - gcc --version && g++ --version

install:
  - pip install meson ninja

script:
  - meson setup builddir
  - meson compile -C builddir
  - meson test -C builddir

